### ISSUE TITLE
GLTF animations

### ISSUE THREAD

**Issue by Javiavan** [AdaRoseCannon/aframe-xr-boilerplate#16]
I have animations in the glb, but it doesn't work.
Any ideas?

**Comment by vincentfretin** [comment]
Do you have the `animation-mixer` component from aframe-extras set on your entity?

**Comment by Javiavan** [comment]
Yeah,
I have it like this:
`<script src="https://cdn.jsdelivr.net/npm/aframe@1.4.1/dist/aframe-master.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/aframe-environment-component@1.3.2/dist/aframe-environment-component.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@fb96ab2/dist/components/sphere-collider.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@fb96ab2/dist/aframe-extras.controls.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/c-frame/physx@v0.1.0/dist/physx.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/aframe-blink-controls@0.4.3/dist/aframe-blink-controls.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/handy-work@3.1.10/build/handy-controls.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/handy-work@3.1.10/build/magnet-helpers.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/aframe-htmlmesh@2.0.1/build/aframe-html.min.js"></script>`


`<a-entity rotation="0 0 0" position="0 0 0" hide-on-enter-ar>
          <a-gltf-model class="navmesh" src="#navmesh-glb" visible="false"></a-gltf-model>
          <a-gltf-model src="#building-glb"
                            id="building"
                            lightmap="src:#bake;intensity: 0; filter:Window,Ceiling,floor;"
                            depthwrite="true"
                            window-replace="Glass"
                            no-tonemapping="Light"
                            shadow="cast:false;receive:true;" animation-mixer></a-gltf-model>
      </a-entity>`

**Comment by Javiavan** [comment]
Ok,
i found the solution. I lacked:
`<script src="https://cdn.jsdelivr.net/gh/c-frame/aframe-extras@7.0.0/dist/aframe-extras.min.js"></script>`
thanks vincent
