### ISSUE TITLE
Stew asset is not currently accessible, breaks live Glitch example

### ISSUE THREAD

**Issue by msub2** [AdaRoseCannon/aframe-xr-boilerplate#18]
Remembered this repo and wanted to use it for another demo I'm doing, but apparently the stew GLTF asset is no longer available at `https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/pot-stew/model.gltf`, so A-Frame hangs during loading and never finishes loading the scene.

**Comment by vincentfretin** [comment]
@AdaRoseCannon I have all the assets locally if you need to reupload to glitch cdn.
Here is the pot-stew model:
[model.zip](https://github.com/AdaRoseCannon/aframe-xr-boilerplate/files/12129679/model.zip)

**Comment by AdaRoseCannon** [comment]
Fixed, thank you!

**Comment by vincentfretin** [comment]
@AdaRoseCannon the glitch is not in sync with the repo, for example the changes of #12 and #14 are not in glitch.

**Comment by AdaRoseCannon** [comment]
Pulled in changes
