### ISSUE TITLE
AR Mode- problem with positioning the object

### ISSUE THREAD

**Issue by holo05** [AdaRoseCannon/aframe-xr-boilerplate#26]
Positioning the piano in AR mode no longer seems to work reliably. The piano is displayed rotated somewhere in the room
Has anyone had the same experience?  (quest 3)

**Comment by vincentfretin** [comment]
Positioning works correctly for me. Rotating with two fingers doesn't work, did it worked before, was it implemented? I don't remember.

**Comment by vincentfretin** [comment]
same behavior on both aframe 1.5.0 and aframe 1.4.2

**Comment by holo05** [comment]
So sorry,  my mistake, I forgot to implement a navmesh! Works perfect. This is without a doubt the best and most complete webxr boilerplate on the net!

Is it technically possible in webxr to switch seamlessly between VR and AR mode and vice versa without leaving the immersive experience?

**Comment by vincentfretin** [comment]
That's not possible to change between an immersive-vr to immersive-ar session of vice versa while the session is started. What you can do is enter AR and if you want to switch to VR, just add back a skybox.
