### ISSUE TITLE
Mobile movement

### ISSUE THREAD

**Issue by Javiavan** [AdaRoseCannon/aframe-xr-boilerplate#3]
Hello,
how can I activate the movement when entering with a mobile device?
With the PC and VR all ok. But with the mobile I can't walk.
Thanks

**Comment by AdaRoseCannon** [comment]
That's a good question, I should probably make a virtual joystick for the cameraRig in the DOM overlay element.

**Comment by AdaRoseCannon** [comment]
Ideally it would just provide a different more appropriate for the format experience on mobile but what that is I dunno

**Comment by polytropoi** [comment]
I use Professor Stemkoski's joystick and extended wasd components (https://github.com/stemkoski/A-Frame-Examples) along with the blink and the simple navmesh (thanks @AdaRoseCannon!) components to get pc/touch/vr movement with navmesh constraint, e.g. https://servicemedia.net/webxr/po1w1b. A bit of useragent sniffing is needed to turn on the joystick on mobile.

**Comment by WarlordCheru** [comment]
Interesting! Would it be possible for the user when entering VR to use the navigation joystick instead of teleportation?

**Comment by Javiavan** [comment]
But what has changed so that you cannot navigate with your fingers from your mobile?

**Comment by Javiavan** [comment]
Ok.
Adding "aframe-extras-min" I got it to work. But some errors appear in the developer tools although testing on different devices seems to work fine

**Comment by dendrofen** [comment]
@AdaRoseCannon feel free to inspect my boilerplate, maybe this could help you
https://github.com/inplayo-com/aframe-boilerplate

**Comment by vincentfretin** [comment]
I would like to add new controls compatible with movement-controls at one point to have two virtual joyticks on mobile and tablet, I created an issue to track that https://github.com/n5ro/aframe-extras/issues/398
