### ISSUE TITLE
Compatibility with aframe master threejs r141

### ISSUE THREAD

**Issue by vincentfretin** [AdaRoseCannon/aframe-xr-boilerplate#5]
When you will try to update your project to use latest aframe master, here is the list of the changes needed in the different libraries so you don't need to search for all the PR I just did :)
`THREE.Math` was removed in threejs r141, it needs to be replaced with `THREE.MathUtils`

You need
- networked-aframe 0.10.0 that includes https://github.com/networked-aframe/networked-aframe/pull/343
- https://github.com/diarmidmackenzie/christmas-scene/pull/2
- https://github.com/n5ro/aframe-extras/pull/377

In the meantime, you can also use:
```
<script src="aframe-master.min.js"></script>
<script>
  THREE.Math = THREE.MathUtils;
</script>
```

**Comment by AdaRoseCannon** [comment]
Is there something else in the Master Branch you need? I am happy to update for the sake of updating, though.

* Perhaps we should move the physics engine locally into the project rather than pegging it at a particular version in someone else's project. Just for convenience sake
* We should probably wait for the PR to aframe-extras to be merged then link to the new build

If you want to make a PR I am happy to check it in

**Comment by vincentfretin** [comment]
No I don't need anything new in aframe master. I was just testing a copy of this project with latest aframe master because I was testing the networked-aframe change for threejs r141 I did.

**Comment by AdaRoseCannon** [comment]
Cool if there is no hurry we can wait. Thanks for raising PRs in the other repos.

**Comment by vincentfretin** [comment]
I want to mention here that physx has been extracted to a separate repository https://github.com/c-frame/physx
I merged some aframe-extras PRs, see https://github.com/c-frame/aframe-extras/issues/5
and networked-aframe 0.11.0 was released.

**Comment by AdaRoseCannon** [comment]
Super!! I don’t really have time to update it myself right now, I’ll get to it when I come back to work although if you have some time to test I’d be happy to take a PR

**Comment by vincentfretin** [comment]
Before we update the project, we can wait that we make releases for `@c-frame/physx`, `@c-frame/sphere-collider` and `@c-frame/movement-controls`
Also there is a new release for blink controls to remove a warning.
`https://cdn.jsdelivr.net/npm/aframe-blink-controls@0.4.1/dist/aframe-blink-controls.min.js`

Are you interested in moving your `simple-navmesh-constraint` component to [c-frame](https://github.com/c-frame/.github)  organization? We can add you as owner to the github and npm organization. We can create a package `@c-frame/simple-navmesh-constraint` and publish it to npm. You can do that yourself or I'll probably do it at one point.
If you have some packages you want to move to c-frame organization to allow other maintainers to help you maintaining them, we'll be happy to have you there, it's up to you of course.

**Comment by AdaRoseCannon** [comment]
Feel free to move it just add an attribution to the file.

**Comment by vincentfretin** [comment]
FYI in aframe-extras repo, `npm run dist` generates a sphere-collider.min.js file, so instead of 
```
  <script>window.module = {exports:{}}</script><!-- Dirty hack to get the sphere collider loading :-( -->
  <script src="https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@master/src/misc/sphere-collider.js"></script>
```
you can use:
```
  <script src="https://cdn.jsdelivr.net/gh/n5ro/aframe-extras@8c9b13a/dist/components/sphere-collider.min.js"></script>
```
The current build on master is up to date.


Also aframe 1.4.0 will be released soon.

**Comment by vincentfretin** [comment]
I see this repository is still using aframe-htmlmesh 1.0.1 and you released 2.0.0, so the html code will need to be updated as well.

I'm just adding notes here while I'm developing my own app where the code diverged a lot from your index.html. I don't have necessary the time right now to update your example and testing it. ;-)

**Comment by AdaRoseCannon** [comment]
no worries, me either lol

**Comment by vincentfretin** [comment]
Another fix needed for aframe master:
- https://github.com/jure/aframe-blink-controls/pull/22

**Comment by vincentfretin** [comment]
Also related, this handy-work PR that is already merged but not released:
- https://github.com/AdaRoseCannon/handy-work/pull/15

**Comment by vincentfretin** [comment]
Fix crash when switching from controllers to hands on Quest (when you put the controllers on the floor):
- https://github.com/n5ro/aframe-extras/pull/385

**Comment by vincentfretin** [comment]
Fix for aframe-htmlmesh when using dynamically created dom element for the UI on the wrist:
- https://github.com/AdaRoseCannon/aframe-htmlmesh/pull/5

**Comment by vincentfretin** [comment]
Released in aframe-htmlmesh 2.0.1, performance fixes 
- https://github.com/AdaRoseCannon/aframe-htmlmesh/pull/7

**Comment by vincentfretin** [comment]
FYI latest build of aframe-extras has the nav-mesh component working again now (https://github.com/n5ro/aframe-extras/pull/388 and https://github.com/n5ro/aframe-extras/pull/390) but there is still an issue with multiple three instances https://github.com/n5ro/aframe-extras/issues/389

**Comment by AdaRoseCannon** [comment]
I'll probably still keep using my simple-navmesh-component I know how it works, but it might be a good idea to point others at one which has more support

**Comment by vincentfretin** [comment]
Some aframe-environment-component fixes are also needed:
- https://github.com/supermedium/aframe-environment-component/pull/78

I added a commented there, the fixes are merged in a c-frame fork https://github.com/c-frame/aframe-environment-component

**Comment by vincentfretin** [comment]
I'll continue spamming here instead of the PR that way we can easily see which issues are closed and which PR are merged.
From my comment in the PR https://github.com/AdaRoseCannon/aframe-xr-boilerplate/pull/7#issuecomment-1339809400
I created two separate issues and even a third one in the aframe-extras repo so we can keep track of them:
- https://github.com/n5ro/aframe-extras/issues/392
- https://github.com/n5ro/aframe-extras/issues/393
- https://github.com/n5ro/aframe-extras/issues/394

**Comment by vincentfretin** [comment]
Note that I'm testing all that with aframe master with three 144. I see aframe master just switched to three 147. I didn't test that yet.
