### ISSUE TITLE
Entities falling through floor after grabbing twice.

### ISSUE THREAD

**Issue by mikolajtkaczyk64** [AdaRoseCannon/aframe-xr-boilerplate#6]
Grabbable entities fall through floor after picking them up when grabbed once.
Device: Oculus Quest 2

**Comment by AdaRoseCannon** [comment]
This is interesting thank you

**Comment by vincentfretin** [comment]
With latest physx in #7 I confirm on Quest when I try to grab a second time, it just slips of my hand, and it goes through the table and floor. I couldn't eat the stew I prepared, I'm hungry now.

**Comment by AdaRoseCannon** [comment]
There are many places where that could go wrong, maybe it’s worth going back to aframe physics system

**Comment by vincentfretin** [comment]
My guess is it have to be something related to your `toggle-physics` component where you change the `physx-body` type between kinematic and dynamic of the entity.

https://github.com/AdaRoseCannon/aframe-xr-boilerplate/blob/924c698c8fca5bd893801ef28b206dd6cc7f90ce/main.js#L103-L111

https://github.com/AdaRoseCannon/aframe-xr-boilerplate/blob/924c698c8fca5bd893801ef28b206dd6cc7f90ce/index.html#L184-L187

@diarmidmackenzie Is there any known issues around that you may know of?
Your [Christmas scene](https://github.com/diarmidmackenzie/christmas-scene) is still with ammo [there](https://diarmidmackenzie.github.io/christmas-scene/)
I thought you switched this experience to physx. I see an old physx branch in the repo. Do you have your experience live with physx somewhere? Does it work?

**Comment by diarmidmackenzie** [comment]
Sorry, I never switched it to physX.  Something I considered doing, but didn't have time for yet.  I anticipated it being a little complicated due to things like switching between kinematic & dynamic (which I read somewhere is unsupported, though I have also seen example code that does this...).

I had a section of that repo where I'd don various physics experiments & tests, so that's where I did my initial physx perf prototyping - which likely created the false impression that christmas-scene used physX.  Sorry for any confusion caused!

**Comment by vincentfretin** [comment]
No worries. Alright so it may indeed just be an issue with physx switching between kinematic and dynamic. We may try to switch back to ammo this example then.

**Comment by vincentfretin** [comment]
While reading the code I found this:
https://github.com/c-frame/physx/blob/a400747e050e49d9a8dfdcb25263de47ed0bd797/src/physics.js#L953-L969
you can use the grabbed state on pickup and remove grabbed state on putdown. Removing the grabbed state before switching to dynamic resolves the impulse issue but the pot stay in the air. I don't know how to reapply gravity on it. I tested several things but nope it doesn't move after putdown. I don't understand how the pot is falling down initially.
```js
AFRAME.registerComponent("toggle-physics", {
  events: {
    pickup: function() {
      this.el.setAttribute('physx-body', 'type', 'kinematic')
      this.el.state.add('grabbed');
    },
    putdown: function() {
      this.el.state.remove('grabbed');
      // this.removeAttribute('physx-body');
      this.el.setAttribute('physx-body', 'type', 'dynamic');
      // this.el.components['physx-body'].toggleGravity();
    }
  }
});
```

**Comment by vincentfretin** [comment]
I'm really dumb. state.add, state.remove doesn't exist... addState, removeState yes.
This code works like a charm, you can't have it simpler:
```js
AFRAME.registerComponent("toggle-physics", {
  events: {
    pickup: function() {
      this.el.addState('grabbed');
    },
    putdown: function() {
      this.el.removeState('grabbed');
    }
  }
});
```
you actually just keep type:dynamic on the pot, and add/remove grabbed state, done.
