### ISSUE TITLE
Oculus 2 issues on boilerplate example

### ISSUE THREAD

**Issue by Mrbside** [AdaRoseCannon/aframe-xr-boilerplate#8]
I tried the glitch example on oculus browser and found this:

-When movement mode activated I cant rotate my rig with right stick
-When using hand tracking, after some time I get a black screen, I still listen audio, when I click menu button on left controller I can see the site on the oculus browser and turn VR again and console is showing this:

aframe-extras.controls.min.js:1 Uncaught TypeError: Cannot read properties of null (reading 'mapping')
    at i.getJoystick (aframe-extras.controls.min.js:1:17649)
    at i.isRotationActive (aframe-extras.controls.min.js:1:15760)
    at i.updateRotation (aframe-extras.controls.min.js:1:15857)
    at i.tick (aframe-extras.controls.min.js:1:15149)
    at HTMLElement.value (a-scene.js:739:34)
    at HTMLElement.value (a-scene.js:789:36)
    at bind.js:12:17
    at onAnimationFrame (three.js:18890:1)
    at XRSession.onAnimationFrame (three.js:9460:1)

Also im trying to implement boilerplate example into my flat VR project, im using aframe-chromakey-material.min.js but its not working, I can hear the audio but video doesn't show 

And finally, is it necessary to activate any flags on oculus browser? or should I leave it as default

Thank you

**Comment by vincentfretin** [comment]
> When movement mode activated I cant rotate my rig with right stick

This was fixed in
- https://github.com/n5ro/aframe-extras/pull/373

> When using hand tracking, after some time I get a black screen, I still listen audio, when I click menu button on left controller I can see the site on the oculus browser and turn VR again and console is showing this:

This was fixed in
- https://github.com/n5ro/aframe-extras/pull/385

Look at #7 for the latest urls to use.

I don't know about aframe-chromakey-material, you probably want to create an issue with a reproducible example on their repository if you didn't.

**Comment by AdaRoseCannon** [comment]
Thanks @vincentfretin, when I get time I will update this example to have the correct URLs. Right now between new baby and job I am a little swamped.

Edit: Oh just remembered your PR #7 which I will merge when it's ready. Thank you for putting that together.

**Comment by vincentfretin** [comment]
No worries, even if you're a little swamped, you were quite reactive merging my PRs :D  Thanks for that.
Yeah you should wait that I debug and fix the issues I found with gamepad-controls before merging the changes of #7. I'll keep updating the PR if I do other fixes anyway. People can just get the changes and modify their glitch on their own.

**Comment by vincentfretin** [comment]
You can close.
